### ISSUE TITLE
Edge case list for model tests

### ISSUE THREAD

**Issue by nsokolnikov** [seadsystem/website#18]
- [ ] Device tries to register itself to a user that doesn't exist
- [ ] Device tries to unregister itself when the user it's attached to does not exist

List will be updating as I think of more.

**Comment by ianlofs** [comment]
I dont think the second one can happen if we make sure the first one cant happen

**Comment by ianlofs** [comment]
Also i dont think that the first one can happen either, the method will fail if a user isnt provided, the only way to get a user is get it from the db. and you cant register a device at the same time as signing up. so i really dont think either of these situations will happen
